### ISSUE TITLE
SVM sends dispValue twice

### ISSUE THREAD

**Issue by tiborauer** [OpenNFT/OpenNFT#24]
I have noticed that SVM sends dispValue twice:
https://github.com/OpenNFT/OpenNFT/blob/389f62472a203bec3927f5963d9aaa9eed3ea6a1/opennft/opennft.py#L633-L638
and
https://github.com/OpenNFT/OpenNFT/blob/389f62472a203bec3927f5963d9aaa9eed3ea6a1/opennft/opennft.py#L790-L800

Do we need both?

**Comment by da0c** [comment]
First display is before data acquisition, and second is after data processing and feedback generation.
Actually, all code under this condition
https://github.com/OpenNFT/OpenNFT/blob/389f62472a203bec3927f5963d9aaa9eed3ea6a1/opennft/opennft.py#L610
is executed at each iteration before data acquisition.

**Comment by ykoush** [comment]
There is indeed some mess there, will check.

**Comment by da0c** [comment]
Fixed SVM on preiteration, discussed and fixed recording of t7 and t8 events.

**Comment by ykoush** [comment]
As discussed with @da0c, preiteration is the time point when the current volume is not yet acquired, which is useful for intermittent feedback type to show an instruction to the participant. However, in more complex feedback types, e.g. using virtual reality performed outside OpenNFT, it could be useful to trigger the display and send UDP data in addition/alternatively to the feedback value send and triggering. This part could stay for SVM UDP 'dispValue' just as an example (that's why reopened).
To avoid confusion, this part is now protocol-specific.
Nevertheless, t7 and t8 in SVM type taken in the Core Python process will likely not be correct and have to be implemented as described in notes to the analyzeEventRecords.m function https://github.com/OpenNFT/OpenNFT/blob/4d96022981d2a4de930e8a2c320a6ff2e0a227dd/tests/analizeTimeVectors/analyzeEventRecords.m#L1.
Times t7, t8, t9, t10 are implemented in ptbscreen.py and displayFeedback.m, because display processes are typically asynchronous to the core Python and Core Matlab processes.

**Comment by ykoush** [comment]
Closed with 76df7e5a20256e78d4631687bb4809e58fad3ea1

**Comment by tiborauer** [comment]
I am afraid I have just checked upon this commit of 234996f74dd647a19165be7c4dc1565dce20132c, which prevent presenting instructions and sending condition labels for continuous NFT. Is that also an intended behaviour?

**Comment by seralouk** [comment]
I am running the SVM example. Everything seems to be working perfectly except the fact that I do not get the feedback value displayed.

I have tried to put a new line in config.py but still no luck.

USE_UDP_FEEDBACK = True

My terminal output looks like this:
```
2021-07-05 03:02:17 | INFO      | opennft:displayMosaicImage - Receiving mosaic image from Matlab (read memmap): 22.04 ms
2021-07-05 03:02:17 | INFO      | opennft:callMainLoopIteration - Display mosaic image: 32.42 ms
2021-07-05 03:02:17 | INFO      | opennft:callMainLoopIteration -   Drawings: 11.40 ms
2021-07-05 03:02:17 | INFO      | opennft:callMainLoopIteration - Elapsed time: 0.4306 s
2021-07-05 03:02:17 | INFO      | opennft:callMainLoopIteration - Call iteration for file "001_000007_000018.dcm"
TIMING: 5 iter - PREPROC MC: 2.455280e-01 s - SMOOTH: 1.688753e-02 s - IGLM: 5.724155e-02 s
2021-07-05 03:02:17 | INFO      | opennft:callMainLoopIteration -   preprocess fMRI Volume: 0.34 s
2021-07-05 03:02:17 | INFO      | opennft:callMainLoopIteration -   preprocess signal: 6.69 ms
sending images to python GUI...
2021-07-05 03:02:17 | INFO      | opennft:displayMosaicImage - Receiving mosaic image from Matlab (read memmap): 21.30 ms
2021-07-05 03:02:17 | INFO      | opennft:displayMosaicImage - Receiving mosaic maps from Matlab: 45.07 ms
2021-07-05 03:02:17 | INFO      | opennft:callMainLoopIteration - Display mosaic image: 0.13 s
2021-07-05 03:02:17 | INFO      | opennft:callMainLoopIteration -   Drawings: 10.69 ms
2021-07-05 03:02:17 | INFO      | opennft:callMainLoopIteration - Elapsed time: 0.5529 s
2021-07-05 03:02:17 | INFO      | opennft:callMainLoopIteration - Call iteration for file "001_000007_000019.dcm"
TIMING: 5 iter - PREPROC MC: 2.376603e-01 s - SMOOTH: 1.816402e-02 s - IGLM: 5.578813e-02 s
2021-07-05 03:02:18 | INFO      | opennft:callMainLoopIteration -   preprocess fMRI Volume: 0.33 s
2021-07-05 03:02:18 | INFO      | opennft:callMainLoopIteration -   preprocess signal: 5.49 ms
sending images to python GUI...
2021-07-05 03:02:18 | INFO      | opennft:displayMosaicImage - Receiving mosaic image from Matlab (read memmap): 23.61 ms
2021-07-05 03:02:18 | INFO      | opennft:displayMosaicImage - Receiving mosaic maps from Matlab: 45.03 ms
2021-07-05 03:02:18 | INFO      | opennft:callMainLoopIteration - Display mosaic image: 0.14 s
2021-07-05 03:02:18 | INFO      | opennft:callMainLoopIteration -   Drawings: 10.36 ms
2021-07-05 03:02:18 | INFO      | opennft:callMainLoopIteration - Elapsed time: 0.5457 s
2021-07-05 03:02:18 | INFO      | opennft:callMainLoopIteration - Call iteration for file "001_000007_000020.dcm"
TIMING: 5 iter - PREPROC MC: 2.438520e-01 s - SMOOTH: 1.755046e-02 s - IGLM: 5.128260e-02 s
2021-07-05 03:02:18 | INFO      | opennft:callMainLoopIteration -   preprocess fMRI Volume: 0.33 s
2021-07-05 03:02:18 | INFO      | opennft:callMainLoopIteration -   preprocess signal: 5.48 ms
sending images to python GUI...
2021-07-05 03:02:18 | INFO      | opennft:displayMosaicImage - Receiving mosaic image from Matlab (read memmap): 23.01 ms
2021-07-05 03:02:19 | INFO      | opennft:displayMosaicImage - Receiving mosaic maps from Matlab: 45.12 ms
2021-07-05 03:02:19 | INFO      | opennft:callMainLoopIteration - Display mosaic image: 0.14 s
2021-07-05 03:02:19 | INFO      | opennft:callMainLoopIteration -   Drawings: 9.64 ms
2021-07-05 03:02:19 | INFO      | opennft:callMainLoopIteration - Elapsed time: 0.5465 s
2021-07-05 03:02:19 | INFO      | opennft:stop - Average elapsed time: 0.3457 s
2021-07-05 03:02:19 | INFO      | opennft:stop - Finished.
```

**Comment by tiborauer** [comment]
@seralouk, Where and how do you want to display the feedback value? If you mean the built-in PTB visualization, then it does not require UDP. If you mean external visualization (via UDP), you may need to provide further details about your setup.

**Comment by seralouk** [comment]
> @seralouk, Where and how do you want to display the feedback value? If you mean the built-in PTB visualization, then it does not require UDP. If you mean external visualization (via UDP), you may need to provide further details about your setup.

I was trying to get the value printed out as in the tutorial. So, not using the PTB. Ideally, I want to use the real-time feedback value to control another aspect of my experiment. 

My setup (toy SVM example): https://imgur.com/a/PjDpyTA

**Comment by ykoush** [comment]
You will get output as a console, just to confirm that the value is sent via UDP. You have to set a mock receiver soft to read UDP output, this you could also do using our receiver simulator, setting sender in OpenNFT accordingly.
As for other questions, right the Issue section is not a forum :), we prefer to keep it fro software related issues. For general questions, there is a tab Discussions: https://github.com/OpenNFT/OpenNFT/discussions
For more specific questions, you can ask in email, or set a meeting: http://opennft.org/References/  http://opennft.org/Courses/

**Comment by seralouk** [comment]
> You will get a console output, just to confirm that the value is sent via UDP. You have to set a mock receiver soft to read the UDP output, this you could also do using our receiver simulator, setting the sender in OpenNFT accordingly.
> As for other questions, right, the Issue section is not a forum :), we prefer to keep it for software related issues. For general questions, there is a tab Discussions: https://github.com/OpenNFT/OpenNFT/discussions
> More specific questions you can ask in email, or set a meeting: http://opennft.org/References/ and http://opennft.org/Courses/

Thank you! I will use the Discussions tabs for questions. Cheers.
